add:
  datas:
    - [1, 1, 2]
    - [100, 400, 300]
    - [-1, 0, 1]
    - [0.1, 0.1, 0.2]
    - [-1, 1, 0]
  ids: ['int', 'zero', 'bignum', 'niuns', 'exp1']


div:
  datas:
    - [1, 1, 1]

# 不怎么会写用例， 过后花时间脑补